[package]
name = "utilitips-app"
version = "0.1.0"
authors = ["Juan Manuel Parrilla Madrid <jparrill@redhat.com>"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
